import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { TripIt } from "../src/tripit";

function requiredEnv(name: string): string {
	const value = process.env[name];
	if (!value) {
		throw new Error(`Missing required env var: ${name}`);
	}
	return value;
}

function addDays(date: Date, days: number): Date {
	const next = new Date(date);
	next.setUTCDate(next.getUTCDate() + days);
	return next;
}

function toDateString(date: Date): string {
	return date.toISOString().slice(0, 10);
}

function extractUuid(response: object, key: string): string {
	const node = (response as Record<string, unknown>)[key] as
		| { uuid?: string }
		| undefined;
	if (!node?.uuid) {
		throw new Error(`Missing uuid in response field "${key}"`);
	}
	return node.uuid;
}

async function main(): Promise<void> {
	const outDir = path.resolve(
		process.env.TRIPIT_SHAPES_DIR ?? "/tmp/tripit-cli-api-shapes",
	);
	await mkdir(outDir, { recursive: true });

	const save = async (name: string, payload: unknown): Promise<void> => {
		const filePath = path.join(outDir, `${name}.json`);
		await writeFile(filePath, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
		console.log(`Saved ${name} -> ${filePath}`);
	};

	const client = new TripIt({
		username: requiredEnv("TRIPIT_USERNAME"),
		password: requiredEnv("TRIPIT_PASSWORD"),
	});

	const created: {
		tripUuid?: string;
		hotelUuid?: string;
		flightUuid?: string;
		transportUuid?: string;
		activityUuid?: string;
	} = {};

	await client.authenticate();

	const now = new Date();
	const tripStart = addDays(now, 30);
	const tripEnd = addDays(now, 33);
	const flightStart = addDays(now, 31);
	const flightEnd = addDays(now, 31);

	try {
		const createTripResponse = await client.createTrip({
			displayName: `codex-shape-test-${Date.now()}`,
			startDate: toDateString(tripStart),
			endDate: toDateString(tripEnd),
			primaryLocation: "San Francisco, US",
		});
		await save("trips.create", createTripResponse);
		created.tripUuid = extractUuid(createTripResponse, "Trip");

		await save("trips.list.current", await client.listTrips(10, 1, false));
		await save("trips.list.past", await client.listTrips(10, 1, true));
		await save("trips.get.initial", await client.getTrip(created.tripUuid));
		await save(
			"trips.update",
			await client.updateTrip({
				uuid: created.tripUuid,
				displayName: `codex-shape-test-updated-${Date.now()}`,
				description: "Generated by scripts/capture-api-responses.ts",
			}),
		);
		await save("trips.get.updated", await client.getTrip(created.tripUuid));

		const createHotelResponse = await client.createHotel({
			tripId: created.tripUuid,
			hotelName: "Codex Hotel",
			checkInDate: toDateString(tripStart),
			checkInTime: "15:00",
			checkOutDate: toDateString(tripEnd),
			checkOutTime: "11:00",
			timezone: "UTC",
			street: "1 Market St",
			city: "San Francisco",
			country: "US",
			state: "CA",
			zip: "94105",
			notes: "shape-test",
		});
		await save("hotels.create", createHotelResponse);
		created.hotelUuid = extractUuid(createHotelResponse, "LodgingObject");
		await save("hotels.get", await client.getHotel(created.hotelUuid));
		await save(
			"hotels.update",
			await client.updateHotel({
				uuid: created.hotelUuid,
				hotelName: "Codex Hotel Updated",
				notes: "shape-test-updated",
			}),
		);

		const createFlightResponse = await client.createFlight({
			tripId: created.tripUuid,
			displayName: "Codex Flight",
			supplierName: "Example Air",
			segments: [
				{
					startDate: toDateString(flightStart),
					startTime: "10:00",
					startTimezone: "UTC",
					endDate: toDateString(flightEnd),
					endTime: "14:00",
					endTimezone: "UTC",
					startCityName: "San Francisco",
					startCountryCode: "US",
					endCityName: "Seattle",
					endCountryCode: "US",
					marketingAirline: "EA",
					marketingFlightNumber: "123",
					serviceClass: "Economy",
				},
			],
			notes: "shape-test",
		});
		await save("flights.create", createFlightResponse);
		created.flightUuid = extractUuid(createFlightResponse, "AirObject");
		await save("flights.get", await client.getFlight(created.flightUuid));
		await save(
			"flights.update",
			await client.updateFlight({
				uuid: created.flightUuid,
				displayName: "Codex Flight Updated",
				notes: "shape-test-updated",
				segment: {
					startTime: "10:30",
					endTime: "14:30",
				},
			}),
		);

		const createTransportResponse = await client.createTransport({
			tripId: created.tripUuid,
			startDate: toDateString(flightStart),
			startTime: "08:00",
			endDate: toDateString(flightStart),
			endTime: "09:00",
			timezone: "UTC",
			startAddress: "1 Market St, San Francisco, CA",
			endAddress: "SFO Airport",
			startLocationName: "Hotel",
			endLocationName: "Airport",
			carrierName: "Rideshare",
			displayName: "Hotel to SFO",
		});
		await save("transport.create", createTransportResponse);
		created.transportUuid = extractUuid(
			createTransportResponse,
			"TransportObject",
		);
		await save(
			"transport.get",
			await client.getTransport(created.transportUuid),
		);
		await save(
			"transport.update",
			await client.updateTransport({
				uuid: created.transportUuid,
				displayName: "Hotel to SFO Updated",
				startTime: "08:15",
				endTime: "09:15",
			}),
		);

		const createActivityResponse = await client.createActivity({
			tripId: created.tripUuid,
			displayName: "Codex Activity",
			startDate: toDateString(flightStart),
			startTime: "16:00",
			endDate: toDateString(flightStart),
			endTime: "18:00",
			timezone: "UTC",
			address: "200 Example St",
			locationName: "Downtown",
			city: "San Francisco",
			state: "CA",
			zip: "94105",
			country: "US",
		});
		await save("activities.create", createActivityResponse);
		created.activityUuid = extractUuid(
			createActivityResponse,
			"ActivityObject",
		);
		await save(
			"activities.get",
			await client.getActivity(created.activityUuid),
		);
		await save(
			"activities.update",
			await client.updateActivity({
				uuid: created.activityUuid,
				displayName: "Codex Activity Updated",
				notes: "shape-test-updated",
			}),
		);

		await save(
			"trips.get.with-objects",
			await client.getTrip(created.tripUuid),
		);

		if (created.activityUuid) {
			await save(
				"activities.delete",
				await client.deleteActivity(created.activityUuid),
			);
			created.activityUuid = undefined;
		}
		if (created.transportUuid) {
			await save(
				"transport.delete",
				await client.deleteTransport(created.transportUuid),
			);
			created.transportUuid = undefined;
		}
		if (created.flightUuid) {
			await save(
				"flights.delete",
				await client.deleteFlight(created.flightUuid),
			);
			created.flightUuid = undefined;
		}
		if (created.hotelUuid) {
			await save("hotels.delete", await client.deleteHotel(created.hotelUuid));
			created.hotelUuid = undefined;
		}
		if (created.tripUuid) {
			await save("trips.delete", await client.deleteTrip(created.tripUuid));
			created.tripUuid = undefined;
		}
	} finally {
		if (created.activityUuid) {
			await client.deleteActivity(created.activityUuid);
		}
		if (created.transportUuid) {
			await client.deleteTransport(created.transportUuid);
		}
		if (created.flightUuid) {
			await client.deleteFlight(created.flightUuid);
		}
		if (created.hotelUuid) {
			await client.deleteHotel(created.hotelUuid);
		}
		if (created.tripUuid) {
			await client.deleteTrip(created.tripUuid);
		}
	}
}

await main();
